# Generated by Django 4.2.20 on 2025-05-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodleQuizAttempt',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('quiz', models.BigIntegerField()),
                ('userid', models.BigIntegerField()),
                ('state', models.CharField(max_length=100)),
                ('timestart', models.BigIntegerField()),
                ('timefinish', models.BigIntegerField()),
                ('sumgrades', models.FloatField()),
            ],
            options={
                'db_table': 'mdl_quiz_attempts',
                'managed': False,
            },
        ),
    ]
