# Generated by Django 4.2.20 on 2025-04-01 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseid', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=50)),
                ('shortname', models.CharField(max_length=50)),
                ('categoryid', models.IntegerField()),
            ],
        ),
    ]
